version: "3"

services:
  srv:
    build: ./srv
    restart: always
    ports:
      - "5002:5002"

  bot:
    build: ./bot
    restart: always
    ports:
      - "5001:5001"

  parity:
    image: parity/parity:stable
    restart: always
    command: --mode active --tracing off --pruning fast --db-compaction hdd --cache-size 1024 --jsonrpc-apis 'eth,web3,personal' --chain kovan --ui-interface all --auto-update=all --max-peers 40 --max-pending-peers 40 --min-peers 40 --allow-ips public --no-discovery --jsonrpc-cors * --ws-origins all --jsonrpc-hosts all --jsonrpc-interface all --ws-interface all ui --base-path /mnt
    volumes:
      - "~/Library/Application\ Support/io.parity.ethereum/:/mnt"
    ports:
      - "8545-8546:8545-8546"
      - "8180:8180"
      - "30303:30303/udp"

  mongo:
    image: mongo
    restart: always
    volumes:
      - "mongo-data:/data/db"

volumes:
  mongo-data:
