version: "3"

services:
  srv:
    build: ./srv
    #image: innoquiz_srv
    restart: always
    ports:
      - "5002:5002"

  bot:
    build: ./bot
    #image: innoquiz_bot
    restart: always
    ports:
      - "5001:5001"

  parity:
    image: parity/parity:v1.8.6
    restart: always
    command: --jsonrpc-apis 'eth,web3,personal' --chain kovan --ui-interface all --jsonrpc-cors * --ws-origins all --jsonrpc-hosts all --jsonrpc-interface all --ws-interface all ui --base-path /mnt
    volumes:
      - "~/Library/Application\ Support/io.parity.ethereum/:/mnt"
    ports:
      - "8545-8546:8545-8546"
      - "8180:8180"
      - "30303:30303/udp"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "mongo-data:/data/db"

volumes:
  mongo-data:
