FROM phusion/baseimage

# Install dependency packages
RUN apt-get clean && apt-get update && apt-get install -y apt-utils python3 python3-dev python3-pip build-essential \
    python3-nose libpq-dev

# Prerequisits for docker
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
RUN apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
# Install docker
RUN apt-get update && apt-get install -y docker-engine

WORKDIR /back
COPY requirements.txt /back/requirements.txt
RUN pip3 install -r requirements.txt
COPY . /back
