FROM phusion/baseimage

# Install dependency packages
RUN apt-get clean && apt-get update && apt-get install -y apt-utils python3 python3-dev python3-pip build-essential \
    python3-nose libpq-dev

WORKDIR /bot
COPY ./bot/requirements.txt /bot/requirements.txt
RUN pip3 install -r requirements.txt
COPY ./bot /bot
